version: '3.4'
services:

  service-provider:
    build: service-provider
    ports:
      - 81:9090

  token-issuer:
    build: token-issuer
    ports:
      - 80:8080
    depends_on:
      - service-provider
